### ISSUE TITLE
IBC Completion

### ISSUE THREAD

**Issue by Wizdave97** [ComposableFi/composable#1441]
This a  tracking issue for the issues that need to be completed to get the ibc implementation to the finish line.
More issues will be added as time passes.

## Pallet Ibc
- [ ] Offchain storage of packets https://github.com/ComposableFi/composable/issues/1440

## Ibc-rs
- [ ] Beefy client connection delay https://github.com/ComposableFi/ibc-rs/issues/37
- [ ] Trusting period for beefy client https://github.com/ComposableFi/ibc-rs/issues/32
- [ ] Track parachain latest heights in beefy client https://github.com/ComposableFi/ibc-rs/issues/46
- [ ] Investigate removing host consensus state verification https://github.com/ComposableFi/ibc-rs/issues/31

## Hyperspace
- [ ] Respect Connection delay https://github.com/ComposableFi/hyperspace/issues/10
- [ ] Observe gas limits when submitting transactions https://github.com/ComposableFi/hyperspace/issues/6
