### ISSUE TITLE
release(mantis): blackbox (solver algorithm) task list

### ISSUE THREAD

**Issue by dzmitry-lahoda** [ComposableFi/composable#4446]
- [x] Post architecture of solver
- [x] OR solution to route transformer (based one some Stephon)
- [ ] Oracle ported from CFFM research (my or Lautaro)
   - [x] Total reserves
   - [x] Price
- [ ] Simulate chains
  - [ ] expand test asserts to ensure results for simulator 
  - [ ] expand tests to all route in Osmosis/Centauri initial tokens + some for Solana/Neutron/Ethereum variants
- [ ] Scaling into from CFFM reasearch into production code
- [ ] Update Osmosis/CVM data integration  (changes API for JSON and mapping of raw data to CVM).
  - [ ] In case of CVM misses things or Osmosis misses things, omit data
- [ ] Devnet test
- [ ] Post ETA constants fees of bridges research post (RFP)
- [ ] Deploy remote blackbox and shares test results
  - [ ] fix SCIP engine build for cloud

**Comment by dzmitry-lahoda** [comment]
released
