### ISSUE TITLE
CI Infrastructure Setup

### ISSUE THREAD

**Issue by haroldsphinx** [ComposableFi/composable#80]
# Continuous Integration with Github Action 

Setting up a Highly Performant and Cost optimized CI Infrastructure for our continuous integration processes, To achieve this, we need to create  the infrastructure that will enable it, this means that we have to setup components like:
- GCP Project to use
- Iac tool to automate this process
- CI Framework that can be reusable by other projects in the organization

## Tasks

- [ ] Setup GCP Project
- [ ] Setup User and Groups
- [ ] Setup Terraform Integration
- [ ] Provision GCP Instances with Terraform

## Output

- [ ] Authorized Users should be able to provision GCP resources using Terraform
- [ ] Provision Github Action Runners using Terraform
